[project]
name = "python-polars"
version = "0.1.0"
description = "Polars feature survey using Python 3."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.29.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
